on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    - name: 'Run Azure image builder'
      uses: azure/imageBuildery@v0
      with: 
        subscriptionID: "xxxxxx"
        ResourceGroupName: "distributorRG"
        imageType: PlatfromImage
        imagebuilderTemplateName: ubuntu1804  ### Standard templates will be part of this action repo
        buildTimeoutInMinutes: 80      
        customizer[0].type: shell     
        customizer[0].name: "runCustomScript"
        customizer[0].source: "https://raw.githubusercontent.com/lnochili/learn-git/master/aib-shellscript.sh"
        customizer[0].destination: "/tmp/aib-hostnameScript.sh"
        customizer[1].type: shell-inline     
        customizer[1].name: "setupBuildPath"
        customizer[1].source: |
            sudo mkdir /buildArtifacts
            sudo cp /tmp/index.html /buildArtifacts/index.html
        distribution-type: ManagedImage
        distribution-imagedef: /subscriptions/<Subscription-ID>/resourceGroups/<GalleryRG>/providers/Microsoft.Compute/images/<imageDefName>
        distribution-location: WestUS2
        distribution-runOutputName: imageDefName.$BuildID  #### this ID needs to be Unique
        distribution-artifactTags: "UbuntuServer 18.04LTS"
    
