#github action for azure image builder

on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
     
    - name: 'Run Azure image builder'
      uses: azure/imageBuildery@v0
      with: 
        imagebuilderTemplate: ubuntu1804
        buildTimeoutInMinutes: 80
        vmType: Standard_D1_v2
        shell: |        
          uri=https://raw.githubusercontent.com/danielsollondon/azvmimagebuilder/master/quickquickstarts/customizeScript.sh
          uri=https://raw.githubusercontent.com/danielsollondon/azvmimagebuilder/master/quickquickstarts/customizeScript2.sh
        file: |
          uri=https://raw.githubusercontent.com/danielsollondon/azvmimagebuilder/master/quickquickstarts/exampleArtifacts/buildArtifacts/index.html
          destination=/tmp/index.html
        shell-inline: |
          sudo mkdir /buildArtifacts
          sudo cp /tmp/index.html /buildArtifacts/index.html
        distribution-type: ManagedImage
        distribution-imageid: /subscriptions/a87c004e-36b1-4eef-b8f3-ec8a539d10ea/resourceGroups/ibLinuxGalleryRG/providers/Microsoft.Compute/images/myBuilderImage
        distribution-location: WestUS2
        distribution-runOutputName: aibLinux
        distribution-artifactTags: |
          source=azVmImageBuilder
          baseosimg=ubuntu1804

