# https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts
# test run

name: Share data between jobs

on: [push]

jobs:
  job_1: 
    name: Azure Image builder run 
    runs-on: ubuntu-latest
    env:
      image-template-name: "UbuntuServer18.04LTS"
      run-output-name: ${{job.job_id}}
      ######Source image details########### 
      type: "PlatformImage"
      publisher: "Canonical"
      offer": "UbuntuServer"
      sku: "18.04-LTS"
      version: "latest"    
     ######Target Distribution details###########
      distributor-resource-group: "iblinuxGalleryRG"
      image-gallery-name: "iblinuxGallery"
      image-definition: "iblinux"
      image-version: "0.1"
      image-location: "West US2"
    ########Custom Scipt location#######
      customizer[0].type: "Shell"
      customizer[0].name: "RunScriptFromSource"
      customizer[0].scriptUri: "https://raw.githubusercontent.com/danielsollondon/azvmimagebuilder/master/quickquickstarts/customizeScript.sh"
    
    steps:  
        - name: 'Checkout Github Action' 
          uses: actions/checkout@master

        - name: azure authentication
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
             
        - name: azure Image builder prerequisites 
          uses: azure/cli@v1
          with:
            resource-group: ${{env.distributor-resource-group}}
            image-gallery-name: ${{env.image-gallery-name}}
            image-definition: ${{env.image-definition}}
            image-version: ${{env.image-version}}
            image-location: ${{env.image-location}}
            inlineScript: |
              chmod +x $GITHUB_WORKSPACE/.github/workflows/azcli-script-prereqs.sh
                         
        - name: 'Update AIB template with inputs'
          run: |
            curl https://raw.githubusercontent.com/raiyanalam/azureImageBuilderAction/master/PlatformImageTemplate-UbuntuLinuxCanonical.json -o PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<subscriptionID>/${{secrets.subscriptionID}/g" PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<rgName>/${{env.distributor-resource-group}}/g" PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<region>/${{env.image-location}}/g" PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<imageName>/${{env.image-definition}}/g" PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<runOutputName>/${{env.run-output-name}}/g" PlatformImageTemplate-UbuntuLinuxCanonical.json
                      
        - name: azure Image builder run
#         uses: azure/cli@v1
          with:
            resource-group: ${{env.distributor-resource-group}}
            image-gallery-name: ${{env.image-gallery-name}}
            image-definition: ${{env.image-definition}}
            aib-template-name: ${{env.aib-template-name}}
            run-output-nme: ${{env.run-output-name}} 
                              
            inlineScript: |
              chmod +x $GITHUB_WORKSPACE/.github/workflows/azcli-imagebuilder-script.sh
                   
    
