# https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts
# test run

name: Share data between jobs

on: [push]

jobs:
  job_1: 
    name: Azure Image builder run 
    runs-on: ubuntu-latest
    env:
      image_template_name: "UbuntuServer18.04LTS"
      run_output_name: ${{job.job_id}}
      ######Source image details########### 
      type: "PlatformImage"
      publisher: "Canonical"
      offer": "UbuntuServer"
      sku: "18.04-LTS"
      version: "latest"    
     ######Target Distribution details###########
      distributor_resource_group: "iblinuxGalleryRG"
      image_gallery_name: "iblinuxGallery"
      image_definition: "iblinux"
      image_version: "0.1"
      image_location: "West US2"
    ########Custom Scipt location#######
    
    steps:  
        - name: 'Checkout Github Action' 
          uses: actions/checkout@master

        - name: azure authentication
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
             
        - name: azure Image builder prerequisites 
          uses: azure/cli@v1
          with:
            ######Source image details########### 
              type: "PlatformImage"
              publisher: "Canonical"
              offer": "UbuntuServer"
              sku: "18.04-LTS"
              version: "latest"    
              os_type: "Linux"
              inlineScript: |
                az role assignment create --assignee cf32a0cc-373c-47c9-9156-0db11f6a6dfc --role Contributor \
                    --scope /subscriptions/{{secrets.AZURE_CREDS.subscriptionID}}/resourceGroups/${{env.distributorResourceGroup}}
                az group create -n ${{env.distributor_resource_group}} -l ${{env.image_location}}
                az sig create -g ${distributor_resource_group}  --gallery-name ${image_gallery_name}
                az sig image-definition create -g ${{env.distributor_resource_group}} --gallery-name ${{env.image_gallery_name}} \
                  --gallery-image-definition ${{env.image_definiation}} --publisher ${{publisher}} --offer ${{offer}}  \
                      --sku ${{sku}}  --os-type ${{os_type}}
                         
        - name: 'Update AIB standard template with inputs'
          customizer.type: "Shell"
          customizer.name: "RunScriptFromSource"
          customizer.scriptUri: "https://raw.githubusercontent.com/raiyanalam/azureImageBuilderAction/master/PlatformImageTemplate-UbuntuLinuxCanonical.json
          run: |
            mkdir $GITHUB_WORKSPACE/aib-local
            curl https://raw.githubusercontent.com/raiyanalam/azureImageBuilderAction/master/PlatformImageTemplate-UbuntuLinuxCanonical.json -o ./aiblocal/PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<subscriptionID>/${{secrets.AZURE_CREDS.subscriptionID}}/g" $GITHUB_WORKSPACE/aib-local/PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<rgName>/${{env.distributor_resource_group}}/g" $GITHUB_WORKSPACE/aib-local/PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<region>/${{env.image_location}}/g" $GITHUB_WORKSPACE/aib-local/PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<imageName>/${{env.image_definition}}/g" $GITHUB_WORKSPACE/aib-local/PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<runOutputName>/${{env.run_output_name}}/g" $GITHUB_WORKSPACE/aib-local/PlatformImageTemplate-UbuntuLinuxCanonical.json
            
                      
        - name: azure Image builder run
          uses: azure/cli@v1
          with:                          
           inlineScript: |
              ###Create Image Template Resource###
                az resource create  --resource-group ${{env.distributor-resource-group}}  \ 
                    --properties @$GITHUB_WORKSPACE/aib-local/PlatformImageTemplate-UbuntuLinuxCanonical.json \
                      --is-full-object  --resource-type Microsoft.VirtualMachineImages/imageTemplates -n ${{env.image-templage-name}}

              #### Run Image Template Resource ###
                az resource invoke-action  --resource-group ${{env.distributor-resource-group}}  \
                      --resource-type  Microsoft.VirtualMachineImages/imageTemplates -n ${{env.image-template-name}} --action Run
                   
    
