
on:
  push


jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        ls -ltr
        pwd
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:        
        name: repo-readme
        path: ./README.md
