# A sample workflow to create VM from shared image gallery!
# az group create --name $vmResourceGroup --location $location
on: [push]

name: create_VM_Using_Shared_Image_Gallery

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account show          
          imgDef="/subscriptions/afc11291-9826-46be-b852-70349146ddf8/resourceGroups/raiyan-rg2/providers/Microsoft.Compute/galleries/rai_sig_eastus/images/rai_ubunut_packer_def/versions/0.0.1"
          
          vmResourceGroup=raiyan-rg2
          location=eastus
          vmName=rai-vm-frm-sig
          adminUsername=moala
          adminPassword=${{ secrets.vm_pwd }}



          az vm create\
            --resource-group $vmResourceGroup \
            --name $vmName \
            --image $imgDef \
            --admin-username $adminUsername \
            --admin-password $adminPassword
